before_install:
  - sudo pip install docutils
  - sudo apt-get install perl-doc
  - curl -L http://cpanmin.us | perl - --sudo App::cpanminus
  - sudo cpanm --installdeps --notest Pod::Simple
  - "/usr/bin/env perldoc -MPod::Simple::XHTML -w html_header: -w html_footer: test/markups/README.pod"
rvm:
  - 1.9.3
  - 2.0.0
notifications:
  disabled: true
bundler_args: --without development
