before_install:
  - sudo pip install docutils
  - curl -L http://cpanmin.us | perl - --sudo App::cpanminus
  - sudo cpanm --installdeps --notest Pod::Simple
rvm:
  - 1.9.3
  - 2.0.0
notifications:
  disabled: true
bundler_args: --without development
