dist: trusty
sudo: required
language: ruby
rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-9.1.9.0
jdk:
  - oraclejdk8
notifications:
  email: false
git:
  depth: 10
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install perl
  - wget -O /tmp/perl6.deb https://github.com/nxadm/rakudo-pkg/releases/download/v2018.02.1/rakudo-pkg-Ubuntu14.04_2018.02.1-01_amd64.deb  && sudo dpkg -i /tmp/perl6.deb && export PATH=$PATH:/.perl6/bin:/opt/rakudo-pkg/bin && install-zef-as-user && zef install Pod::To::HTML
  - curl -L http://cpanmin.us | perl - --sudo App::cpanminus
  - sudo cpanm --installdeps --notest Pod::Simple
  - sudo pip install docutils
cache:
  - bundler
  - pip
env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"
matrix:
 allow_failures:
   - rvm: jruby-9.1.9.0
