before_install: sudo pip install docutils
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby-19mode
  - jruby-head
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: oraclejdk7 
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7 
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.1.1
      jdk: oraclejdk7 
    - rvm: 2.1.1
      jdk: openjdk7
notifications:
  disabled: true
