language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.1
  - jruby-19mode
jdk:
  - oraclejdk8
notifications:
  email: false
git:
  depth: 10
before_install: pip install docutils
cache:
  - bundler
  - pip
